version: '3.9'

services:

  front:
    container_name: ${COMPOSE_PROJECT_NAME}_front
    build:
      dockerfile: ./docker/${ENV}/front/Dockerfile
      context: .
    expose:
      - 3000
    working_dir: /app
    volumes:
      - ./../front:/app:rw,delegated
      - /app/node_modules
      - /app/.next
    environment:
      - VIRTUAL_HOST=front.gauthiercart.dev
      - VIRTUAL_PORT=3000
    networks:
      - gauthiercart_network
    env_file: docker/${ENV}/front/front.env
    command: tail -f /dev/null

  nginx-proxy:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DOCKER_DATA}/${COMPOSE_PROJECT_NAME}_nginx-vhost:/etc/nginx/vhost.d
      - ${DOCKER_DATA}/${COMPOSE_PROJECT_NAME}_nginx-share:/usr/share/nginx/html
      - ${DOCKER_DATA}/${COMPOSE_PROJECT_NAME}_nginx-certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/nginx/nginx-timeout.conf:/etc/nginx/conf.d/nginx-timeout.conf
    networks:
      - gauthiercart_network
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    restart: unless-stopped

networks:
  gauthiercart_network:
    driver: bridge